# Generated by Django 5.2.7 on 2025-11-14 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='created_by',
            new_name='user',
        ),
    ]
