# Generated by Django 5.2.7 on 2025-11-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profilemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('faculty_type', models.CharField(choices=[('Science', 'Science'), ('Business', 'Business'), ('Arts', 'Arts')], max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PostModel',
        ),
    ]
