# Generated by Django 5.2.7 on 2025-11-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ebook_teachermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(default='W3Schools', max_length=100)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Web', 'Web Development'), ('Database', 'Database')], max_length=50)),
                ('file_url', models.URLField()),
                ('cover_image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
