# Generated by Django 5.2.7 on 2025-11-21 11:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_question_option_quiz_question_quiz_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiple_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='quiz',
            name='passing_score',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='random_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=0, help_text='Time limit in minutes (0 = no limit)'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
