# Generated by Django 5.2.7 on 2025-11-21 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_quizattempt_quiz_remove_quizattempt_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CourseRegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('student_id', models.CharField(max_length=100, null=True)),
                ('semester', models.IntegerField(null=True)),
                ('section', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('profile_image', models.ImageField(null=True, upload_to='media/profile_image/')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.departmentmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentModel',
        ),
    ]
