# Generated by Django 5.2.7 on 2025-11-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_userinfomodel_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseregistrationmodel',
            name='department',
        ),
    ]
