# Generated by Django 5.2.7 on 2025-11-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_courseregistrationmodel_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseregistrationmodel',
            name='profile_image',
        ),
    ]
