# Generated by Django 5.2.7 on 2025-11-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_courseregistrationmodel_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_image/'),
        ),
    ]
