# Generated by Django 5.2.8 on 2025-11-23 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_profilemodel_bio_alter_profilemodel_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='address',
        ),
    ]
